.TH asteroids-example 1 "30 Jan 2025" raylib-asteroids "asteroids-example manual"
.SH NAME
asteroids-example \- Asteroids in C with Raylib and the Whisker library
.SH SYNOPSIS
asteroids-example
.SH DESCRIPTION
Asteroids in C with Raylib and the Whisker library
.SH OPTIONS

.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
ElGatoPanzon (contact@elgatopanzon.io)
